### ISSUE TITLE
Dataset open-source?

### ISSUE THREAD

**Issue by ChenhongyiYang** [yt4766269/SceneEgo#1]
Hi,

Thank you for your great work. May I ask if you have any plan to open-source the dataset?

**Comment by JunrQ** [comment]
![企业微信截图_16915676671978](https://github.com/yt4766269/SceneEgo/assets/9657134/4d2f5b59-1e66-47cb-9f18-ea26ab708495)

**Comment by yt4766269** [comment]
Hello, the dataset has already been made publicly available. Please check the project homepage: https://people.mpi-inf.mpg.de/~jianwang/projects/sceneego/index.htm

Very sorry for the late response. I did not find the issue 2 weeks ago

**Comment by yt4766269** [comment]
If you have any further issues, please contact me via E-mail: jianwang AT mpi-inf.mpg.de
