### ISSUE TITLE
FileNotFoundError error

### ISSUE THREAD

**Issue by xiaogangw** [yt4766269/SceneEgo#2]
Thanks for your excellent work! 

While I was running the demo.py, I got an `FileNotFoundError: [Errno 2] No such file or directory: '/HPS/Mo2Cap2Plus1/work/Mo2Cap2Finetune/logs/finetune2D_spin_without_da_iter_0_new/checkpoints/6.pth.tar'`

If I change the `model.backbone.checkpoint` in `sceneego.yaml` to the downloaded checkpoint path, I got `RuntimeError: Error(s) in loading state_dict for PoseResNet`.

Could you please help on this?

**Comment by yt4766269** [comment]
Hello xiaogangw,

Sorry for the bugs in my repo. I tried to solve the problem. Can you check if it can work?

Jian
